name: ci

on:
  push:
    branch:
      - main
  pull_request:

jobs:
  build_test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: prerequisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libjansson-dev
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: |
          autoreconf -fi
          ./configure
          make
