on:
  push:
    tags:
    - 'v*'

name: release

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: prerequisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libjansson-dev libcurl4-openssl-dev
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: |
          autoreconf -fi
          ./configure
          make dist
      - name: get version
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: true
      - name: upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./circa-${{ env.VERSION }}.tar.gz
          asset_name: circa-${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip
